name: Level1_place_new

task_type: "pickplace"
controller_type: "pickplace"

mode: "collect"

usd_path: "assets/chemistry_lab/lab_001/lab_001.usd"
target_path: "/World/target_plat"


max_episodes: 100

infer:
  type: "remote"
  obs_names: {"camera_1_rgb": 'camera_1_rgb', "camera_2_rgb": 'camera_2_rgb'}

  policy_model_path: ""
  policy_config_path: ""
  normalizer_path: ""

  host: "127.0.0.1"
  port: 8000
  n_obs_steps: 1
  timeout: 30
  max_retries: 3

task:
  max_steps: 2000
  obj_paths:
    - path: "/World/beaker2"
      position_range:
        x: [0.19, 0.34]
        y: [0.10, 0.25]
        z: [0.84, 0.84]

    - path: "/World/target_plat"
      position_range:



cameras:
  # 外部相机 (根据图片参数配置)
  # Translation: [1.36277, -0.16629, 2.01971]
  # Euler Angles: [40.87947, 0.0, 90.34175]

  - prim_path: "/World/Camera"
    name: "camera_1"
    translation: [2.9, -0.16, 3.4]
    resolution: [640, 480]
    focal_length: 5
    euler_angles: [-0.29,46.90,90.40]  # XYZ欧拉角 (度数)
    image_type: "rgb"

  # 手腕相机 (保持不变)
  - prim_path: "/World/Franka/panda_hand/arm_camera"
    name: "camera_2"
    translation: [-0.2, 0, -0.02]
    resolution: [640, 480]
    focal_length: 1
    orientation: [0.20083, 0.67799, -0.67799, -0.20083]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: gzip

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
